// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Compensation struct {
	ID            string   `json:"id"`
	Timestamp     *string  `json:"timestamp,omitempty"`
	AgeRange      *string  `json:"age_range,omitempty"`
	Industry      *string  `json:"industry,omitempty"`
	JobTitle      *string  `json:"job_title,omitempty"`
	AnnualSalary  *float64 `json:"annual_salary,omitempty"`
	Currency      *string  `json:"currency,omitempty"`
	Location      *string  `json:"location,omitempty"`
	Experience    *string  `json:"experience,omitempty"`
	JobContext    *string  `json:"job_context,omitempty"`
	OtherCurrency *string  `json:"other_currency,omitempty"`
}

type Query struct {
}
